SSAFY/movie-pjt/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('',views.index,name='index'),
    path('<int:user_pk>',views.detail,name='detail'),
    path('<int:user_pk>/follow', views.follow, name='follow'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

SSAFY/movie-pjt/movie_pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from movies import views

urlpatterns = [
    path('',views.list),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

SSAFY/movie-pjt/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.list, name='list'),
    path('actors/', views.actorlist, name='actorlist'),
    path('directors/', views.directorlist, name='directorlist'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/score', views.score_create, name='score_create'),
    path('<int:movie_pk>/score/<int:score_pk>/delete/',views.score_delete,name='score_delete'),
    path('search/', views.search, name='search'),
    path('<int:movie_pk>/like/', views.like, name='like'),
    path('genremovie/<int:genre_pk>/', views.genremovie, name='genremovie'),
    path('yearmovie/<int:year>', views.yearmovie, name='yearmovie'),
    path('agemovie/<age>/', views.agemovie, name='agemovie'),
    path('manywatching/',views.manywatching,name='manywatching'),
    path('notwatching/',views.notwatching,name='notwatching'),
    path('genrerecommend/',views.genrerecommend,name='genrerecommend'),
    path('actordetail/<int:actor_pk>',views.actordetail,name='actordetail'),
    path('directordetail/<int:director_pk>',views.directordetail,name='directordetail'),
    path('<int:actor_pk>/likeactor/',views.likeactor,name='likeactor'),
    path('<int:director_pk>/likedirector/',views.likedirector,name='likedirector'),
    path('actorrecommend/',views.actorrecommend,name='actorrecommend'),
    path('directorrecommend/',views.directorrecommend,name='directorrecommend'),
    path('mypage/',views.mypage,name='mypage'),
]

SSAFY/movie-pjt/movies/models.py
from django.shortcuts import reverse
from django.db import models
from django.conf import settings
# Create your models here.

class Genre(models.Model):
    name = models.CharField(max_length=20)
    def __str__(self):
        return self.name

class Actor(models.Model):
    name = models.CharField(max_length=30)
    image_url = models.TextField()
    likeactor_users = models.ManyToManyField(settings.AUTH_USER_MODEL,blank=True,related_name='like_actors')
    
    def likeactor_count(self):
        return self.likeactor_users.count()
        
    def __str__(self):
        return self.name
    
class Director(models.Model):
    name = models.CharField(max_length=30)
    image_url = models.TextField()
    likedirector_users = models.ManyToManyField(settings.AUTH_USER_MODEL,blank=True,related_name='like_directors')
    
    def likedirector_count(self):
        return self.likedirector_users.count()
        
    def __str__(self):
        return self.name
    
class Movie(models.Model):
    title = models.CharField(max_length=30)
    code = models.IntegerField()
    dates = models.DateField(blank=True)
    age = models.TextField()
    watch = models.IntegerField()
    audience = models.IntegerField()
    poster_url = models.TextField()
    description = models.TextField()
    genre = models.ManyToManyField(Genre, related_name='genremovies')
    score_users = models.ManyToManyField(settings.AUTH_USER_MODEL, 
                                    through='Score',
                                    related_name='score_movies'
                                    )
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')
    actors = models.ManyToManyField(Actor, related_name='actormovies')
    directors = models.ManyToManyField(Director, related_name='directormovies')
    
    def like_count(self):
        return self.like_users.count()
    def get_absolute_url(self):
        return reverse("movies:detail", args=[self.pk])


class Score(models.Model):
    content = models.CharField(max_length=140)
    value = models.IntegerField()
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    

SSAFY/movie-pjt/movies/forms.py
from django import forms
from .models import Score



class ScoreForm(forms.ModelForm):
    class Meta:
        model = Score
        fields = ('content', 'value')

SSAFY/movie-pjt/movies/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Movie, Score, Genre, Actor, Director
from django.core.paginator import Paginator
from django.http import JsonResponse, HttpResponseBadRequest
from django.contrib.auth.decorators import login_required
from .forms import ScoreForm
import json
import urllib.request


# 네브바 - 검색 로그인 홈 
# 메인 페이지 - 탑50 (다음영화처럼보이게), 추천영화
# 검색 - 검색 결과에서 디테일 넘어갈수있게 + 팔로우기능
# 디테일 - 태그

# Create your views here.
def list(request):
    genres = Genre.objects.all()
    ages = ['전체 관람가','12세 관람가','15세 관람가','청소년 관람불가']
    years = [2019,2018,2017,2016,2015,2014,2013,2012,2011,2010,2009]
    movies = Movie.objects.order_by('-pk')
    paginator = Paginator(movies, 9)
    page = request.GET.get('page')
    contacts = paginator.get_page(page)
    context = {'movies':movies, 'contacts': contacts, 'genres':genres, 'ages':ages, 'years':years, 'key':'list'}
    return render(request, 'movies/list.html',context)
    
def actorlist(request):
    genres = Genre.objects.all()
    ages = ['전체 관람가','12세 관람가','15세 관람가','청소년 관람불가']
    years = [2019,2018,2017,2016,2015,2014,2013,2012,2011,2010,2009]
    actors = Actor.objects.order_by('-pk')
    paginator = Paginator(actors, 9)
    page = request.GET.get('page')
    contacts = paginator.get_page(page)
    context = {'actors':actors, 'contacts': contacts, 'genres':genres, 'ages':ages, 'years':years, 'key':'actor'}
    return render(request, 'movies/list.html',context)
    
def directorlist(request):
    genres = Genre.objects.all()
    ages = ['전체 관람가','12세 관람가','15세 관람가','청소년 관람불가']
    years = [2019,2018,2017,2016,2015,2014,2013,2012,2011,2010,2009]
    directors = Director.objects.order_by('-pk')
    paginator = Paginator(directors, 9)
    page = request.GET.get('page')
    contacts = paginator.get_page(page)
    context = {'directors':directors, 'contacts': contacts, 'genres':genres, 'ages':ages, 'years':years, 'key':'director'}
    return render(request, 'movies/list.html',context)

def detail(request,movie_pk):
    genres = Genre.objects.all()
    ages = ['전체 관람가','12세 관람가','15세 관람가','청소년 관람불가']
    years = [2019,2018,2017,2016,2015,2014,2013,2012,2011,2010,2009]
    movie = Movie.objects.get(pk=movie_pk)
    # movie.watch += 1
    # movie.save()
    form = ScoreForm()
    context = {'movie':movie,'form':form, 'genres':genres,'ages':ages, 'years':years}
    return render(request,'movies/detail.html',context)
    
@login_required
def score_create(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    if request.method == 'POST':
        form = ScoreForm(request.POST)
        if form.is_valid():
            score = form.save(commit=False)
            score.user = request.user
            score.movie = movie
            score.save()
            return redirect(movie)
    return redirect(movie)

def score_delete(request,movie_pk,score_pk):
    if request.method == 'POST':
        score = Score.objects.get(pk=score_pk)
        score.delete()
    return redirect('movies:detail',movie_pk)

def search(request):
    genres = Genre.objects.all()
    ages = ['전체 관람가','12세 관람가','15세 관람가','청소년 관람불가']
    years = [2019,2018,2017,2016,2015,2014,2013,2012,2011,2010,2009]
    itext = request.POST.get('itext')
    movies = Movie.objects.filter(title__contains=itext)
    if len(movies) == 0 : movieheight = 2.5
    else : 
        if len(movies) % 3 == 0: 
            movieheight = len(movies) // 3 *40 + 10
        else:
            movieheight = len(movies) // 3 * 40 + 50
    actors = Actor.objects.filter(name__contains=itext)
    directors = Director.objects.filter(name__contains=itext)
    context = {'movies':movies, 'actors':actors,'directors':directors, 'genres':genres,'ages':ages, 'years':years, 'itext':itext, 
    'movieheight':movieheight }
    return render(request, 'movies/search.html', context=context)
            

def like(request, movie_pk):
    genres = Genre.objects.all()
    ages = ['전체 관람가','12세 관람가','15세 관람가','청소년 관람불가']
    years = [2019,2018,2017,2016,2015,2014,2013,2012,2011,2010,2009]
    movie = get_object_or_404(Movie, pk=movie_pk)
    user = request.user
    if user in movie.like_users.all():
        movie.like_users.remove(user)
    else:
        movie.like_users.add(user)
    return redirect('movies:detail',movie_pk)

def genremovie(request,genre_pk):
    genres = Genre.objects.all()
    ages = ['전체 관람가','12세 관람가','15세 관람가','청소년 관람불가']
    years = [2019,2018,2017,2016,2015,2014,2013,2012,2011,2010,2009]
    genre1 = Genre.objects.get(pk=genre_pk)
    movies = Movie.objects.filter(genre=genre1).order_by('-pk')
    # 장르 pk를 땡겨오고 그거에 관련된 영화만 
    paginator = Paginator(movies, 9)
    page = request.GET.get('page')
    contacts = paginator.get_page(page)
    context = {'movies':movies, 'contacts': contacts, 'genres':genres, 'ages':ages, 'years':years}
    return render(request, 'movies/list.html',context)

def yearmovie(request, year):
    genres = Genre.objects.all()
    ages = ['전체 관람가','12세 관람가','15세 관람가','청소년 관람불가']
    years = [2019,2018,2017,2016,2015,2014,2013,2012,2011,2010,2009]
    if year == 2009:
        movies = Movie.objects.filter(dates__startswith=200).order_by('-dates')
    else:
        movies = Movie.objects.filter(dates__startswith=year).order_by('-dates')
    paginator = Paginator(movies, 9)
    page = request.GET.get('page')
    contacts = paginator.get_page(page)
    context = {'movies':movies, 'contacts': contacts, 'genres':genres, 'ages':ages, 'years':years}
    return render(request,'movies/list.html',context)
    

def agemovie(request, age):
    genres = Genre.objects.all()
    ages = ['전체 관람가','12세 관람가','15세 관람가','청소년 관람불가']
    years = [2019,2018,2017,2016,2015,2014,2013,2012,2011,2010,2009]
    movies = Movie.objects.filter(age=age).order_by('-pk')
    paginator = Paginator(movies, 9)
    page = request.GET.get('page')
    contacts = paginator.get_page(page)
    context = {'movies':movies, 'contacts': contacts, 'genres':genres, 'ages':ages, 'years':years}
    return render(request, 'movies/list.html', context)
    
def manywatching(request):
    genres = Genre.objects.all()
    ages = ['전체 관람가','12세 관람가','15세 관람가','청소년 관람불가']
    years = [2019,2018,2017,2016,2015,2014,2013,2012,2011,2010,2009]
    movies = Movie.objects.all().order_by('-audience')
    paginator = Paginator(movies, 9)
    page = request.GET.get('page')
    contacts = paginator.get_page(page)
    context = {'movies':movies, 'contacts': contacts, 'genres':genres, 'ages':ages, 'years':years }
    return render(request,'movies/list.html',context)
    
def notwatching(request):
    genres = Genre.objects.all()
    ages = ['전체 관람가','12세 관람가','15세 관람가','청소년 관람불가']
    years = [2019,2018,2017,2016,2015,2014,2013,2012,2011,2010,2009]
    movies = Movie.objects.all().order_by('-audience')
    lists = []
    for movie in movies:
        if not movie in request.user.like_posts.all():
            lists.append(movie)
            if len(lists) == 3 : break
    paginator = Paginator(lists, 9)
    page = request.GET.get('page')
    contacts = paginator.get_page(page)
    context = {'movies':movies, 'contacts': contacts, 'genres':genres, 'ages':ages, 'years':years ,'lists':lists}
    return render(request,'movies/list.html',context)
    
def genrerecommend(request):
    genres = Genre.objects.all()
    ages = ['전체 관람가','12세 관람가','15세 관람가','청소년 관람불가']
    years = [2019,2018,2017,2016,2015,2014,2013,2012,2011,2010,2009]
    movies = Movie.objects.all().order_by('-audience')
    lists = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
    result = []
    for movie in movies :
        if movie in request.user.like_posts.all():
            for genre in movie.genre.all():
                lists[genre.id-1] += 1
    a = Genre.objects.filter(id=lists.index(max(lists))+1)
    for amovie in a[0].genremovies.all().order_by('-audience'):
        if not amovie in request.user.like_posts.all():
            result.append(amovie)
            if len(result)==3:
                break
    paginator = Paginator(result, 9)
    page = request.GET.get('page')
    contacts = paginator.get_page(page)
    context = {'movies':movies, 'contacts': contacts, 'genres':genres, 'ages':ages, 'years':years ,'lists':lists}
    return render(request,'movies/list.html',context)
    
def actorrecommend(request):
    genres = Genre.objects.all()
    ages = ['전체 관람가','12세 관람가','15세 관람가','청소년 관람불가']
    years = [2019,2018,2017,2016,2015,2014,2013,2012,2011,2010,2009]
    movies = Movie.objects.all().order_by('-audience')
    result = []
    for movie in movies :
        for actor in movie.actors.all():
            if actor in request.user.like_actors.all():
                print(actor)
                result.append(movie)
                break
        if len(result) > 2 : break
    paginator = Paginator(result, 9)
    page = request.GET.get('page')
    contacts = paginator.get_page(page)
    context = {'movies':movies, 'contacts': contacts, 'genres':genres, 'ages':ages, 'years':years ,'result':result}
    return render(request,'movies/list.html',context)

def directorrecommend(request):
    genres = Genre.objects.all()
    ages = ['전체 관람가','12세 관람가','15세 관람가','청소년 관람불가']
    years = [2019,2018,2017,2016,2015,2014,2013,2012,2011,2010,2009]
    movies = Movie.objects.all().order_by('-audience')
    result = []
    for movie in movies :
        for director in movie.directors.all():
            if director in request.user.like_directors.all():
                result.append(movie)
                break
        if len(result) > 2 : break
    paginator = Paginator(result, 9)
    page = request.GET.get('page')
    contacts = paginator.get_page(page)
    context = {'movies':movies, 'contacts': contacts, 'genres':genres, 'ages':ages, 'years':years ,'result':result}
    return render(request,'movies/list.html',context)



# 관심 영화 뿐 아니라 관심 배우 누르는 기능 추가해서 관심 배우가 출연한 영화 추천 알고리즘 
def actordetail(request,actor_pk):
    genres = Genre.objects.all()

SSAFY/movie-pjt/movies/templates/movies/actordetail.html
{% extends 'base.html' %}

{% block body %}
<div class='container' style='margin-top:10px; margin-right:100px'>
    <div class='row'>
        <div style='display: inline; width:400px; margin-right:30px; margin-left:30px'>
            
            <!--<p>누적 관객수 : {{movie.audience}}</p>-->
            <p><img src="{{actor.image_url}}" style='height:400px; width:400px;'></p>
        </div>
        <div style='display: inline; width:650px'>
            
            <h4><b>
            <p><b><h4>{{actor.name}}</h4></b></p>
            <hr>
            <h5>출연영화</h5>
            {% for movie in actor.actormovies.all %}
                <p><a href="{% url 'movies:detail' movie.id %}">{{movie.title}}</a></p>
            {% endfor %}
        </div>
    </div>
    <hr>    
    {% if user in actor.likeactor_users.all %}
        <a href="{% url 'movies:likeactor' actor.pk %}">
        좋아요 취소</a>
    {% else %}
        <a href="{% url 'movies:likeactor' actor.pk %}">
        좋아요</a>
    {% endif %}
    {{actor.likeactor_count}}명

</div>
{% endblock %}

SSAFY/movie-pjt/movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block body %}
<div class='container' style='margin-top:10px;'>
    <div class='row'>
        <div style='display: inline; width:400px; margin-right:30px; margin-left:30px'>
            <h3></h3>
            <a href="{% url 'movies:list' %}">뒤로</a>
            <!--<p>누적 관객수 : {{movie.audience}}</p>-->
            <p><img src="{{movie.poster_url}}" style='height:400px; width:400px;'></p>
        </div>
        <div style='display: inline; width:650px'>
            <h4>영화소개</h4><br><br>
            <p>{{movie.description}}</p>
            <hr>
            <h5>감독</h5>
            {% for director in movie.directors.all %}
                <p><a href="{% url 'movies:directordetail' director.id %}">{{director}}</a></p>
            {% endfor %}
            <hr>
            <h5>출연배우</h5>
            {% for actor in movie.actors.all %}
                <p><a href="{% url 'movies:actordetail' actor.id %}">{{actor}}</a></p>
            {% endfor %}
        </div>
    </div>
    <hr>    
    {% if user in movie.like_users.all %}
        <a href="{% url 'movies:like' movie.pk %}">좋아요 취소</a>
    {% else %}
        <a href="{% url 'movies:like' movie.pk %}">좋아요</a>
    {% endif %}
    {{movie.like_count}}명
    
    <p>평점 등록</p>    
    {% if user.is_authenticated %}
        <form method="POST" action="{% url 'movies:score_create' movie.pk%}">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="평점 등록">
        </form>
    {% else %}
        <p>로그인을 하셔야만 평점 등록가능합니다. <a href="{% url 'accounts:login' %}">로그인 하기</a></p>
    {% endif %}
    
    {% for score in movie.score_set.all %}
        <p><a href="{% url 'accounts:detail' user.pk %}">{{ score.user.username }}</a> : {{ score.value }}점</p>
        <p>{{ score.content }}</p>
    {% if user == score.user %}
        <form action="{% url 'movies:score_delete' movie.pk score.pk %}" method="POST" style="display: inline">
            {% csrf_token %}
            <input type="submit" value="삭제">
        </form>
    {% endif %}
    <hr>
    {% endfor %}
</div>
{% endblock %}

SSAFY/movie-pjt/movies/templates/movies/directordetail.html
{% extends 'base.html' %}

{% block body %}
<div class='container' style='margin-top:10px; margin-right:100px;'>
    <div class='row'>
        <div style='display: inline; width:400px; margin-right:30px; margin-left:30px'>
            <h3>{{movie.title}}</h3>
            <p><img src="{{director.image_url}}" style='height:400px; width:400px;'></p>
        </div>
        <div style='display: inline; width:650px'>
            <h4><b>감독정보</b></h4><br>
            <p><b><h4>{{director.name}}</h4></b></p>
            <hr>
            <h5>연출 영화</h5>
            {% for movie in director.directormovies.all %}
                <p><a href="{% url 'movies:detail' movie.id %}">{{movie.title}}</a></p>
            {% endfor %}
        </div>
    </div>
    <hr>    
    {% if user in director.likedirector_users.all %}
        <a href="{% url 'movies:likedirector' director.pk %}">좋아요 취소</a>
    {% else %}
        <a href="{% url 'movies:likedirector' director.pk %}">좋아요</a>
    {% endif %}
    {{director.likedirector_count}}명

</div>
{% endblock %}

SSAFY/movie-pjt/movies/templates/movies/list.html
{% extends 'base.html' %}

{% load bootstrap_pagination %}
{% block body %}

<div class="container">
    
    {% if key == 'actor' %}
    <div class="row mx-auto">
        {% for actor in contacts %}
            <div class = 'col-md-4'>
                <div class="card m-3" style="width: 18rem; height:20rem;">
                    <img src="{{actor.image_url}}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{actor.name}}</h5>
                        
                        <a href="{% url 'movies:actordetail' actor.pk %}">배우 상세보기</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {% elif key == 'director' %}
    <div class="row mx-auto">
        {% for director in contacts %}
            <div class = 'col-md-4'>
                <div class="card m-3" style="width: 18rem; height:20rem;">
                    <img src="{{director.image_url}}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{director.name}}</h5>
                        
                        <a href="{% url 'movies:directordetail' director.pk %}">감독 상세보기</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {% else %}
    <div class="row mx-auto">
        {% for movie in contacts %}
            <div class = 'col-md-4'>
                <div class="card m-3" style="width: 18rem; height:40rem;">
                    <img src="{{movie.poster_url}}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{movie.title}}</h5>
                        {% if movie.genre.all.length >= 3 %}
                            movie.genre.all = [movie.genre[0],movie.genre[1],movie.genre[2]]
                        {% endif %}
                        <p>장르 : {% for ge in movie.genre.all %}
                            {{ge}}
                        {% endfor %}</p>
                        <p class="card-text">관객수 : {{movie.audience}}</p>
                        <a href="{% url 'movies:detail' movie.pk %}">영화 상세보기</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {% endif %}
    <nav aria-label="Page navigation example">
        <div class="row d-flex justify-content-center">
            <div class="pagination">
                <span class="step-links">
                    {% bootstrap_paginate contacts %}
                </span>
            </div>
        </div>
    </nav>
</div>


{% endblock %}

SSAFY/movie-pjt/movies/templates/movies/mypage.html
{% extends 'base.html' %}

{% load bootstrap_pagination %}
{% block body %}
<div class="container" style="margin-top:30px">
    <hr>
    <div class="container" style="height:{{movieheight}}rem">
        <h2>영화</h2>
        <div class="row mx-auto">
            {% for movie in likemovies %}
                <div class = 'col-md-4'>
                    <div class="card m-3" style="width: 18rem; height:40rem;">
                        <img src="{{movie.poster_url}}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{movie.title}}</h5>
                            {% if movie.genre.all.length >= 3 %}
                                movie.genre.all = [movie.genre[0],movie.genre[1],movie.genre[2]]
                            {% endif %}
                            <p>장르 : {% for ge in movie.genre.all %}
                                {{ge}}
                            {% endfor %}</p>
                            <p class="card-text">관객수 : {{movie.audience}}</p>
                            <a href="{% url 'movies:detail' movie.pk %}">영화 상세보기</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <hr>
    <div class="container">
        <h2>배우</h2>
        <div class="row mx-auto">
            {% for actor in likeactors %}
                <div class = 'col-md-4'>
                    <div class="card m-3" style="width: 18rem; height:20rem;">
                        <img src="{{actor.image_url}}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{actor.name}}</h5>
                            
                            <a href="{% url 'movies:actordetail' actor.pk %}">배우 상세보기</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
        <hr>
    <div class="container">
        <h2>감독</h2>
        <div class="row mx-auto">
            {% for director in likedirectors %}
                <div class = 'col-md-4'>
                    <div class="card m-3" style="width: 18rem; height:20rem;">
                        <img src="{{director.image_url}}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{director.name}}</h5>
                            
                            <a href="{% url 'movies:directordetail' director.pk %}">감독 상세보기</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <hr>
</div>


{% endblock %}

SSAFY/movie-pjt/movies/templates/movies/search.html
{% extends 'base.html' %}

{% load bootstrap_pagination %}
{% block body %}
<div class="container" style="margin-top:30px">
    <h1>'{{itext}}' 검색 결과입니다</h1>
    <hr>
    <div class="container" style="height:{{movieheight}}rem">
        <h2>영화</h2>
        <div class="row mx-auto">
            {% for movie in movies %}
                <div class = 'col-md-4'>
                    <div class="card m-3" style="width: 18rem; height:40rem;">
                        <img src="{{movie.poster_url}}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{movie.title}}</h5>
                            {% if movie.genre.all.length >= 3 %}
                                movie.genre.all = [movie.genre[0],movie.genre[1],movie.genre[2]]
                            {% endif %}
                            <p>장르 : {% for ge in movie.genre.all %}
                                {{ge}}
                            {% endfor %}</p>
                            <p class="card-text">관객수 : {{movie.audience}}</p>
                            <a href="{% url 'movies:detail' movie.pk %}">영화 상세보기</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <hr>
    <div class="container">
        <h2>배우</h2>
        <div class="row mx-auto">
            {% for actor in actors %}
                <div class = 'col-md-4'>
                    <div class="card m-3" style="width: 18rem; height:20rem;">
                        <img src="{{actor.image_url}}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{actor.name}}</h5>
                            
                            <a href="{% url 'movies:actordetail' actor.pk %}">배우 상세보기</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
        <hr>
    <div class="container">
        <h2>감독</h2>
        <div class="row mx-auto">
            {% for director in directors %}
                <div class = 'col-md-4'>
                    <div class="card m-3" style="width: 18rem; height:20rem;">
                        <img src="{{director.image_url}}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{director.name}}</h5>
                            
                            <a href="{% url 'movies:directordetail' director.pk %}">감독 상세보기</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <hr>
</div>


{% endblock %}

SSAFY/movie-pjt/movies/templates/movies/searching.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {% for item in items %}
        {{ item.link }} <hr> <!-- item.link에서  code= 뒤에 있는 숫자 가져오기 -->
        {{item.title}} : <img src = "{{item.image}}"><br>
    {% endfor %}
</body>
</html>