SSAFY/movie-pjt/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('',views.index,name='index'),
    path('<int:user_pk>',views.detail,name='detail'),
    path('<int:user_pk>/follow', views.follow, name='follow'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

SSAFY/movie-pjt/movie_pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from movies import views

urlpatterns = [
    path('',views.list),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

SSAFY/movie-pjt/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.list, name='list'),
    path('actors/', views.actorlist, name='actorlist'),
    path('directors/', views.directorlist, name='directorlist'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/score', views.score_create, name='score_create'),
    path('<int:movie_pk>/score/<int:score_pk>/delete/',views.score_delete,name='score_delete'),
    path('search/', views.search, name='search'),
    path('<int:movie_pk>/like/', views.like, name='like'),
    path('genremovie/<int:genre_pk>/', views.genremovie, name='genremovie'),
    path('yearmovie/<int:year>', views.yearmovie, name='yearmovie'),
    path('agemovie/<age>/', views.agemovie, name='agemovie'),
    path('manywatching/',views.manywatching,name='manywatching'),
    path('notwatching/',views.notwatching,name='notwatching'),
    path('genrerecommend/',views.genrerecommend,name='genrerecommend'),
    path('actordetail/<int:actor_pk>',views.actordetail,name='actordetail'),
    path('directordetail/<int:director_pk>',views.directordetail,name='directordetail'),
    path('<int:actor_pk>/likeactor/',views.likeactor,name='likeactor'),
    path('<int:director_pk>/likedirector/',views.likedirector,name='likedirector'),
    path('actorrecommend/',views.actorrecommend,name='actorrecommend'),
    path('directorrecommend/',views.directorrecommend,name='directorrecommend'),
    path('mypage/',views.mypage,name='mypage'),
]

SSAFY/movie-pjt/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
# Create your models here.
class User(AbstractUser):
    followers = models.ManyToManyField(
                        settings.AUTH_USER_MODEL,
                        related_name='followings'
                        )

SSAFY/movie-pjt/movies/models.py
from django.shortcuts import reverse
from django.db import models
from django.conf import settings
# Create your models here.

class Genre(models.Model):
    name = models.CharField(max_length=20)
    def __str__(self):
        return self.name

class Actor(models.Model):
    name = models.CharField(max_length=30)
    image_url = models.TextField()
    likeactor_users = models.ManyToManyField(settings.AUTH_USER_MODEL,blank=True,related_name='like_actors')
    
    def likeactor_count(self):
        return self.likeactor_users.count()
        
    def __str__(self):
        return self.name
    
class Director(models.Model):
    name = models.CharField(max_length=30)
    image_url = models.TextField()
    likedirector_users = models.ManyToManyField(settings.AUTH_USER_MODEL,blank=True,related_name='like_directors')
    
    def likedirector_count(self):
        return self.likedirector_users.count()
        
    def __str__(self):
        return self.name
    
class Movie(models.Model):
    title = models.CharField(max_length=30)
    code = models.IntegerField()
    dates = models.DateField(blank=True)
    age = models.TextField()
    watch = models.IntegerField()
    audience = models.IntegerField()
    poster_url = models.TextField()
    description = models.TextField()
    genre = models.ManyToManyField(Genre, related_name='genremovies')
    score_users = models.ManyToManyField(settings.AUTH_USER_MODEL, 
                                    through='Score',
                                    related_name='score_movies'
                                    )
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')
    actors = models.ManyToManyField(Actor, related_name='actormovies')
    directors = models.ManyToManyField(Director, related_name='directormovies')
    
    def like_count(self):
        return self.like_users.count()
    def get_absolute_url(self):
        return reverse("movies:detail", args=[self.pk])


class Score(models.Model):
    content = models.CharField(max_length=140)
    value = models.IntegerField()
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    

SSAFY/movie-pjt/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCustomCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ['username','email','last_name','first_name',]

SSAFY/movie-pjt/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import get_user_model
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_POST
from .models import User
from .forms import UserCustomCreationForm

    
def index(request):
    users = User.objects.order_by('-pk')
    context = {'users':users}
    return render(request,'accounts/index.html',context)
     
# from django.db.models import Max
# def detail(request, user_pk):
#     User = get_user_model()
#     user = get_object_or_404(User, pk=user_pk)
#     followings = user.followings.annotate(max_value=Max('score__value'))
#     context = {'user_info': user,'followings':followings}
#     return render(request, 'accounts/detail.html', context)

from django.db.models import Prefetch, Count
from movies.models import Score


#** 자세하게 공부(prefetch_related, select_related)
def detail(request, user_pk):
    User = get_user_model()
    user = get_object_or_404(User.objects.annotate(
                            followers_count=Count('followers'), 
                                followings_count=Count('followings')
                                ), pk=user_pk)
    followings = user.followings.prefetch_related(
                                            Prefetch('score_set',
                                            queryset=Score.objects.select_related('movie').order_by('-value'),
                                            to_attr='score_set_value_order'
                                            ))
    context = {'user_info': user, 'followings': followings}
    return render(request, 'accounts/detail.html', context)


def follow(request, user_pk):
    User = get_user_model()
    target_user = get_object_or_404(User, pk=user_pk)
    if request.user in target_user.followers.all():
        target_user.followers.remove(request.user)
    else:
        target_user.followers.add(request.user)
    return redirect('accounts:detail', user_pk)
    
# Create your views here.
@require_http_methods(["GET", "POST"])
def signup(request):
    if request.user.is_authenticated: # 이미 로그인이 되어 있다면
        return redirect('movies:list')
    if request.method == 'POST': 
        user_form = UserCustomCreationForm(request.POST)
        if user_form.is_valid():
            user = user_form.save()
            auth_login(request, user)
            return redirect('movies:list')
    else:
        user_form = UserCustomCreationForm()
    context = {'form': user_form}
    return render(request, 'accounts/forms.html', context)

def login(request):
    if request.user.is_authenticated:
        return redirect('movies:list')
    if request.method == 'POST':
        login_form = AuthenticationForm(request, request.POST)
        if login_form.is_valid():
            auth_login(request, login_form.get_user())
            return redirect('movies:list')
    else:
        login_form = AuthenticationForm()
    context = {'form': login_form}
    return render(request, 'accounts/forms.html', context)

@login_required
def logout(request):
    auth_logout(request)
    return redirect('movies:list')

SSAFY/movie-pjt/accounts/templates/accounts/detail.html
{% extends 'base.html' %}

{% block body %}
    <p><b>user id</b> : <b>{{ user_info.username }}</b></p>
    <p><b>following</b> : <b>{{ user_info.followings.all.count }}</b></p>
    <p><b>follower</b>: <b>{{ user_info.followers.all.count }}</b></p>
    {% for post in user_info.post_set.all %}
        <h3>content : {{post.content}}</h3>
    {% endfor %}
    
    {% if user != user_info %}
        {% if user in user_info.followers.all %}
            <a href="{% url 'accounts:follow' user_info.pk %}"><h2>unfollowing</h2></a>
        {% else %}
            <a href="{% url 'accounts:follow' user_info.pk %}"><h2>following</h2></a>
        {% endif %}
    {% endif %}
    
    <p>팔로워 목록</p>
    {% for user in user_info.followers.all %}
        <a href="{% url 'accounts:detail' user.pk %}" >{{user}}</a>
    {% endfor %}
    <p>팔로잉 목록</p>
    {% for user in user_info.followings.all %}
        <a href="{% url 'accounts:detail' user.pk %}">{{user}}</a>
    {% endfor %}

<hr>
<p>내가 작성한 리뷰 목록</p>
{% for score in user_info.score_set.all %}
    <p>{{ score.movie.title }} </p>
    <p>{{ score.content }}</p>
    <p>{{ score.value }}</p>
    <p>====================</p>
{% endfor %}
<br>
<p>내 친구가 좋아하는 영화</p>
{% for user_follow in followings %}
    <p>{{ user_follow.score_set_value_order.0.movie.title }}</p>
    <p>{{ user_follow.score_set_value_order.0.value }}점</p>
{% endfor %}

<!--<p>친구가 관람한 영화 목록</p>-->
<!--{% for user_follow in user_info.followings.all %}-->
<!--    {% for lists in user_follow.score_set.all %}-->
<!--        <p><a href="{% url 'accounts:detail' user.pk %}">{{lists.user}}</a> : {{lists.movie.title}} / {{lists.value}} 점</p>-->
<!--    {% endfor %}-->
<!--{% endfor %}-->

<!--<hr>-->
    
<!--<p>친구의 추천 영화</p>-->
<!--{% for user_follow in followings %}-->
<!--    {% for lists in user_follow.score_set.all %}-->
<!--        {% if lists.value == user_follow.max_value %}-->
<!--            <p><a href="{% url 'accounts:detail' user.pk %}">{{lists.user}}</a>  님이 {{lists.movie.title}}을  {{lists.value}}점으로 평가했습니다.</p>-->
<!--        {% endif %}-->
<!--    {% endfor %}-->
<!--{% endfor %}-->


{% endblock %}

SSAFY/movie-pjt/accounts/templates/accounts/forms.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <br><br><br><br>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p}}
            <input type="submit" value="진행">
        </form>
</div>
{% endblock %}

SSAFY/movie-pjt/accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% block body %}

{% for user in users %}
    <h2><a href="{% url 'accounts:detail' user.pk %}" >{{user}}</a></h2>
{% endfor %}

{% endblock %}